# Generated by Django 5.0 on 2024-02-09 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kabkota',
            name='dapil_dpr',
        ),
        migrations.RemoveField(
            model_name='kabkota',
            name='dapil_dprdprov',
        ),
        migrations.RemoveField(
            model_name='kecamatan',
            name='dapil_kabkota',
        ),
        migrations.RemoveField(
            model_name='kecamatan',
            name='laki_laki',
        ),
        migrations.RemoveField(
            model_name='kecamatan',
            name='perempuan',
        ),
    ]
