# Generated by Django 5.0 on 2024-02-09 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lhp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahapan', models.IntegerField(choices=[(1, 'Masa Tenang'), (2, 'Persiapan Pemungutan Suara'), (3, 'Pemungutan dan Penghitungan Suara'), (3, 'Pengawasan Lainnya')])),
                ('bentuk', models.IntegerField(choices=[(1, 'Langsung'), (2, 'Tidak Langsung')])),
                ('tujuan', models.CharField(max_length=255)),
                ('sasaran', models.CharField(max_length=255)),
                ('waktu', models.CharField(max_length=255)),
                ('tempat', models.CharField(max_length=255)),
                ('uraian', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LhpMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='lhp/')),
                ('lhp', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='laporanhasil.lhp')),
            ],
        ),
    ]
