# Generated by Django 5.0 on 2024-02-09 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpdRiMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='dpd/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ptps', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dpdri', to='accounts.userpengawastps')),
            ],
        ),
        migrations.CreateModel(
            name='CekDpdRi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='perolehansuara.dpdrimedia')),
            ],
        ),
        migrations.CreateModel(
            name='DprdKabKotaMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='dprdkab/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ptps', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dprdkabkota', to='accounts.userpengawastps')),
            ],
        ),
        migrations.CreateModel(
            name='CekDprdKabKota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='perolehansuara.dprdkabkotamedia')),
            ],
        ),
        migrations.CreateModel(
            name='DprdProvMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='dprdprov/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ptps', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dprdprov', to='accounts.userpengawastps')),
            ],
        ),
        migrations.CreateModel(
            name='CekDprdProv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='perolehansuara.dprdprovmedia')),
            ],
        ),
        migrations.CreateModel(
            name='DprRiMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='dpr/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ptps', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dprri', to='accounts.userpengawastps')),
            ],
        ),
        migrations.CreateModel(
            name='CekDprRi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='perolehansuara.dprrimedia')),
            ],
        ),
        migrations.CreateModel(
            name='PpwpMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='ppwp/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ptps', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ppwp', to='accounts.userpengawastps')),
            ],
        ),
        migrations.CreateModel(
            name='CekPpwp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='perolehansuara.ppwpmedia')),
            ],
        ),
    ]
