# Generated by Django 5.0 on 2024-02-09 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wilayah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('role', models.IntegerField(choices=[(1, 'Bawaslu'), (2, 'Pengawas TPS')], default=2)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPengawasTps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kabkota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah.kabkota')),
                ('kecamatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah.kecamatan')),
                ('keldesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah.keldesa')),
                ('maker', models.ForeignKey(limit_choices_to={'role': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maker', to=settings.AUTH_USER_MODEL)),
                ('provinsi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah.provinsi')),
                ('tps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah.tps')),
                ('user', models.OneToOneField(limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StartReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ptps', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userpengawastps')),
            ],
        ),
        migrations.CreateModel(
            name='EndReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ptps', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userpengawastps')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='users/profile_pictures')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='users/cover_photo')),
                ('jk', models.IntegerField(blank=True, choices=[(1, 'Laki-laki'), (2, 'Perempuan')], null=True)),
                ('alamat', models.CharField(blank=True, max_length=255, null=True)),
                ('rt', models.CharField(blank=True, null=True)),
                ('rw', models.CharField(blank=True, null=True)),
                ('wa', models.CharField(blank=True, max_length=16, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userpengawastps',
            name='userprofile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile'),
        ),
        migrations.CreateModel(
            name='WhetherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Cerah'), (2, 'Mendung'), (3, 'Hujan')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ptps', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userpengawastps')),
            ],
        ),
    ]
